[tasks.lint]
description = "Apply lint"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets", "--", "--deny", "warnings"]
dependencies = ["fmt-check", "sort-check"]

[tasks.fmt-check]
description = "Check format"
command = "cargo"
args = ["fmt", "--check"]

[tasks.sort-check]
description = "Check if Cargo.toml dependencies sorted"
install_crate = { crate_name = "cargo-sort"}
command = "cargo"
args = ["sort", "--workspace", "--check"]

[tasks.cli-release-build]
env = { "CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS" = ["clc-cli"]}
run_task = { name = "release-build", fork = true}

[tasks.sort]
description = "sort Cargo.toml dependencies"
install_crate = { crate_name = "cargo-sort"}
command = "cargo"
args = ["sort", "--workspace"]

[tasks.bench]
description = "Run benchmarks"
install_crate = { crate_name = "cargo-criterion"}
command = "cargo"
args = ["criterion"]

[tasks.benchmark]
alias = "bench"

[tasks.test]
description = "Run nextest"
install_crate = { crate_name = "cargo-nextest"}
command = "cargo"
args = ["nextest", "run"]

[tasks.publish-engine]
description = "Publish clc-engine package"
command = "cargo"
args = ["publish", "--package", "clc-engine"]

[config]
# https://github.com/sagiegurari/cargo-make#disabling-workspace-support
default_to_workspace = false
